# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob
- stage: ABDeploy
  jobs:
  - job: ABDeployJob
    steps:
    - bash: echo ABDeployJob
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob

steps:
- script: echo Job1 Step1!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
